<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-maccatalyst;net9.0-windows10.0.19041.0</TargetFrameworks>
	
	 <OutputType>Exe</OutputType>
    <RootNamespace>ShareTrader</RootNamespace>

    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <WindowsPackageType>None</WindowsPackageType>


    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <ApplicationTitle>ShareTrader</ApplicationTitle>
    <ApplicationId>com.companyname.sharetrader</ApplicationId>

    <ApplicationDisplayVersion>1.0.13</ApplicationDisplayVersion>
    <ApplicationVersion>13</ApplicationVersion>
 
    <DefaultLanguage>en</DefaultLanguage>   
    
</PropertyGroup>

  <!-- MAUI resources -->
  <ItemGroup>
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

    <MauiImage Include="Resources\Images\*" />
    <MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

    <MauiFont Include="Resources\Fonts\*" />

    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <!-- Files excluded from compilation -->
  <ItemGroup>
    <Compile Remove="PortfolioItem.cs" />
    <Compile Remove="Services\DownloadServices.cs" />
  </ItemGroup>

  <!-- NuGet packages -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.8" />

    <PackageReference Include="Syncfusion.Licensing" Version="34.1.31" />
    <PackageReference Include="Syncfusion.Maui.Core" Version="34.1.31" />
    <PackageReference Include="Syncfusion.Maui.DataGrid" Version="34.1.31" />
    <PackageReference Include="Syncfusion.Maui.Charts" Version="34.1.31" />
    <PackageReference Include="Syncfusion.Maui.Inputs" Version="34.1.31" />
  </ItemGroup>

  <!-- Project folders -->
  <ItemGroup>
    <Folder Include="Helpers\" />
    <Folder Include="Data\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <!-- XAML code-behind -->
  <ItemGroup>
    <Compile Update="Pages\AddCompanyPopup.xaml.cs">
      <DependentUpon>AddCompanyPopup.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <!-- XAML compilation -->
  <ItemGroup>
    <MauiXaml Update="Pages\AddCompanyPopup.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>

</Project>